artifact_location: /home/jj/github-classroom/STRDeepRL/week-2-build-your-own-ppo-jsa1142/submission/mlflow/500060631980982079
creation_time: 1695308348828
experiment_id: '500060631980982079'
last_update_time: 1695308348828
lifecycle_stage: active
name: 1v1_death_match_baseline
